-- supabase/seeds/seed_channels.sql
-- Seed 50 placeholder channels for Plug TV
-- Uses the placeholder logo: /logos/placeholders/default-tv.svg

-- Note: This file assumes the countries, categories, and languages seeds have been applied.

INSERT INTO public.channels (slug, name, description, country_id, category_id, language_id, logo_url, website_url, embed_allowed, embed_url, tags)
VALUES
('bbc-news','BBC News','British public service broadcaster — news coverage and live programming.',
  (SELECT id FROM public.countries WHERE slug='uk'),
  (SELECT id FROM public.categories WHERE slug='news'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.bbc.co.uk/news', false, NULL, ARRAY['news','public']),

('itv','ITV','UK commercial TV network offering entertainment and news.',
  (SELECT id FROM public.countries WHERE slug='uk'),
  (SELECT id FROM public.categories WHERE slug='entertainment'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.itv.com', false, NULL, ARRAY['tv','entertainment']),

('channel-4','Channel 4','UK public-service television broadcaster with entertainment and factual programming.',
  (SELECT id FROM public.countries WHERE slug='uk'),
  (SELECT id FROM public.categories WHERE slug='entertainment'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.channel4.com', false, NULL, ARRAY['tv','uk']),

('sky-sports','Sky Sports','Sports broadcasting network providing live sports coverage (UK).',
  (SELECT id FROM public.countries WHERE slug='uk'),
  (SELECT id FROM public.categories WHERE slug='sports'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.skysports.com', false, NULL, ARRAY['sports','live']),

('cnn','CNN','International news network covering breaking news and live events.',
  (SELECT id FROM public.countries WHERE slug='usa'),
  (SELECT id FROM public.categories WHERE slug='news'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://edition.cnn.com', false, NULL, ARRAY['news','international']),

('fox-news','Fox News','US-based news channel focusing on current events and commentary.',
  (SELECT id FROM public.countries WHERE slug='usa'),
  (SELECT id FROM public.categories WHERE slug='news'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.foxnews.com', false, NULL, ARRAY['news','us']),

('abc-news','ABC News','American news broadcaster with live coverage and programs.',
  (SELECT id FROM public.countries WHERE slug='usa'),
  (SELECT id FROM public.categories WHERE slug='news'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://abcnews.go.com', false, NULL, ARRAY['news','us']),

('cbs-news','CBS News','US news division of the CBS network.',
  (SELECT id FROM public.countries WHERE slug='usa'),
  (SELECT id FROM public.categories WHERE slug='news'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.cbsnews.com', false, NULL, ARRAY['news','broadcast']),

('nbc-news','NBC News','American news broadcaster covering national and global news.',
  (SELECT id FROM public.countries WHERE slug='usa'),
  (SELECT id FROM public.categories WHERE slug='news'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.nbcnews.com', false, NULL, ARRAY['news','usa']),

('cbc-news','CBC News','Canadian broadcaster with national news coverage.',
  (SELECT id FROM public.countries WHERE slug='canada'),
  (SELECT id FROM public.categories WHERE slug='news'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.cbc.ca/news', false, NULL, ARRAY['news','canada']),

('ctv','CTV','Canadian television network with entertainment and news programming.',
  (SELECT id FROM public.countries WHERE slug='canada'),
  (SELECT id FROM public.categories WHERE slug='entertainment'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.ctv.ca', false, NULL, ARRAY['tv','canada']),

('abc-aus','ABC Australia','Australian Broadcasting Corporation — news and public programming.',
  (SELECT id FROM public.countries WHERE slug='australia'),
  (SELECT id FROM public.categories WHERE slug='news'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.abc.net.au/news', false, NULL, ARRAY['news','australia']),

('sbs','SBS Australia','Australian public broadcaster with multicultural and multilingual content.',
  (SELECT id FROM public.countries WHERE slug='australia'),
  (SELECT id FROM public.categories WHERE slug='entertainment'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.sbs.com.au', false, NULL, ARRAY['multicultural','tv']),

('nhk-world','NHK World','Japan Broadcasting Corporation international service (English-language).',
  (SELECT id FROM public.countries WHERE slug='japan'),
  (SELECT id FROM public.categories WHERE slug='news'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www3.nhk.or.jp/nhkworld', false, NULL, ARRAY['news','japan']),

('tv-tokyo','TV Tokyo','Japanese entertainment and general programming.',
  (SELECT id FROM public.countries WHERE slug='japan'),
  (SELECT id FROM public.categories WHERE slug='entertainment'),
  (SELECT id FROM public.languages WHERE code='ja'),
  '/logos/placeholders/default-tv.svg','https://www.tv-tokyo.co.jp', false, NULL, ARRAY['entertainment','japan']),

('kbs-world','KBS World','South Korean broadcaster offering international content.',
  (SELECT id FROM public.countries WHERE slug='south-korea'),
  (SELECT id FROM public.categories WHERE slug='entertainment'),
  (SELECT id FROM public.languages WHERE code='ko'),
  '/logos/placeholders/default-tv.svg','https://kbsworld.kbs.co.kr', false, NULL, ARRAY['korea','entertainment']),

('arirang','Arirang','International English-language broadcaster from South Korea.',
  (SELECT id FROM public.countries WHERE slug='south-korea'),
  (SELECT id FROM public.categories WHERE slug='news'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.arirang.com', false, NULL, ARRAY['news','korea']),

('france24','France 24','International news network broadcasting in multiple languages.',
  (SELECT id FROM public.countries WHERE slug='france'),
  (SELECT id FROM public.categories WHERE slug='news'),
  (SELECT id FROM public.languages WHERE code='fr'),
  '/logos/placeholders/default-tv.svg','https://www.france24.com', false, NULL, ARRAY['news','france']),

('dw','Deutsche Welle','German international broadcaster with news and documentary programs.',
  (SELECT id FROM public.countries WHERE slug='germany'),
  (SELECT id FROM public.categories WHERE slug='news'),
  (SELECT id FROM public.languages WHERE code='de'),
  '/logos/placeholders/default-tv.svg','https://www.dw.com', false, NULL, ARRAY['news','germany']),

('zdf','ZDF','German public-service television broadcaster with entertainment and factual shows.',
  (SELECT id FROM public.countries WHERE slug='germany'),
  (SELECT id FROM public.categories WHERE slug='entertainment'),
  (SELECT id FROM public.languages WHERE code='de'),
  '/logos/placeholders/default-tv.svg','https://www.zdf.de', false, NULL, ARRAY['tv','germany']),

('rai','RAI','Italian public broadcasting company with national programming.',
  (SELECT id FROM public.countries WHERE slug='italy'),
  (SELECT id FROM public.categories WHERE slug='entertainment'),
  (SELECT id FROM public.languages WHERE code='it'),
  '/logos/placeholders/default-tv.svg','https://www.raiplay.it', false, NULL, ARRAY['italy','tv']),

('rainews','RAI News','Italian news service providing national and international news.',
  (SELECT id FROM public.countries WHERE slug='italy'),
  (SELECT id FROM public.categories WHERE slug='news'),
  (SELECT id FROM public.languages WHERE code='it'),
  '/logos/placeholders/default-tv.svg','https://www.rainews.it', false, NULL, ARRAY['news','italy']),

('rtve','RTVE','Spanish public broadcasting service with general programming and news.',
  (SELECT id FROM public.countries WHERE slug='spain'),
  (SELECT id FROM public.categories WHERE slug='entertainment'),
  (SELECT id FROM public.languages WHERE code='es'),
  '/logos/placeholders/default-tv.svg','https://www.rtve.es', false, NULL, ARRAY['spain','tv']),

('eurosport','Eurosport','Pan-European sports network covering live sports events and highlights.',
  (SELECT id FROM public.countries WHERE slug='france'),
  (SELECT id FROM public.categories WHERE slug='sports'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.eurosport.com', false, NULL, ARRAY['sports','europe']),

('espn','ESPN','American sports network covering a wide range of sporting events and news.',
  (SELECT id FROM public.countries WHERE slug='usa'),
  (SELECT id FROM public.categories WHERE slug='sports'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.espn.com', false, NULL, ARRAY['sports','usa']),

('dazn','DAZN','Global sports subscription service providing live streaming and highlights.',
  (SELECT id FROM public.countries WHERE slug='uk'),
  (SELECT id FROM public.categories WHERE slug='sports'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.dazn.com', false, NULL, ARRAY['sports','streaming']),

('al-jazeera','Al Jazeera English','International news organization providing news and documentaries.',
  (SELECT id FROM public.countries WHERE slug='qatar'),
  (SELECT id FROM public.categories WHERE slug='news'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.aljazeera.com', false, NULL, ARRAY['news','international']),

('alarabiya','Al Arabiya','Arabic-language news channel with regional and global coverage.',
  (SELECT id FROM public.countries WHERE slug='saudi-arabia'),
  (SELECT id FROM public.categories WHERE slug='news'),
  (SELECT id FROM public.languages WHERE code='ar'),
  '/logos/placeholders/default-tv.svg','https://english.alarabiya.net', false, NULL, ARRAY['news','arabic']),

('mbc','MBC','Middle Eastern entertainment and general programming network.',
  (SELECT id FROM public.countries WHERE slug='saudi-arabia'),
  (SELECT id FROM public.categories WHERE slug='entertainment'),
  (SELECT id FROM public.languages WHERE code='ar'),
  '/logos/placeholders/default-tv.svg','https://www.mbc.net', false, NULL, ARRAY['entertainment','middle-east']),

('geo-tv','Geo TV','Pakistani news and entertainment channel offering national coverage.',
  (SELECT id FROM public.countries WHERE slug='pakistan'),
  (SELECT id FROM public.categories WHERE slug='entertainment'),
  (SELECT id FROM public.languages WHERE code='ur'),
  '/logos/placeholders/default-tv.svg','https://www.geo.tv', false, NULL, ARRAY['pakistan','tv']),

('ptv','PTV','Pakistan Television Corporation — national broadcaster with news and programming.',
  (SELECT id FROM public.countries WHERE slug='pakistan'),
  (SELECT id FROM public.categories WHERE slug='news'),
  (SELECT id FROM public.languages WHERE code='ur'),
  '/logos/placeholders/default-tv.svg','https://www.ptv.com.pk', false, NULL, ARRAY['news','pakistan']),

('btv','BTV','Bangladesh Television — official broadcaster with national programming.',
  (SELECT id FROM public.countries WHERE slug='bangladesh'),
  (SELECT id FROM public.categories WHERE slug='news'),
  (SELECT id FROM public.languages WHERE code='bn'),
  '/logos/placeholders/default-tv.svg','https://www.btv.gov.bd', false, NULL, ARRAY['bangladesh','news']),

('doordarshan','Doordarshan','India\'s public service broadcaster with news and cultural programming.',
  (SELECT id FROM public.countries WHERE slug='india'),
  (SELECT id FROM public.categories WHERE slug='news'),
  (SELECT id FROM public.languages WHERE code='hi'),
  '/logos/placeholders/default-tv.svg','https://ddnews.gov.in', false, NULL, ARRAY['india','news']),

('sonyliv','SonyLIV','Indian entertainment platform and broadcaster offering TV shows and movies (info page).',
  (SELECT id FROM public.countries WHERE slug='india'),
  (SELECT id FROM public.categories WHERE slug='entertainment'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.sonyliv.com', false, NULL, ARRAY['entertainment','india']),

('hotstar','Disney+ Hotstar','Streaming platform with live sports and entertainment (India region).',
  (SELECT id FROM public.countries WHERE slug='india'),
  (SELECT id FROM public.categories WHERE slug='entertainment'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.hotstar.com', false, NULL, ARRAY['streaming','india']),

('ntv-nepal','NTV Nepal','Nepal Television — national broadcaster for Nepal.',
  (SELECT id FROM public.countries WHERE slug='nepal'),
  (SELECT id FROM public.categories WHERE slug='news'),
  (SELECT id FROM public.languages WHERE code='ne'),
  '/logos/placeholders/default-tv.svg','https://ntv.org.np', false, NULL, ARRAY['nepal','news']),

('adaderana','Ada Derana','Sri Lankan news channel and digital news platform.',
  (SELECT id FROM public.countries WHERE slug='sri-lanka'),
  (SELECT id FROM public.categories WHERE slug='news'),
  (SELECT id FROM public.languages WHERE code='si'),
  '/logos/placeholders/default-tv.svg','https://www.adaderana.lk', false, NULL, ARRAY['sri-lanka','news']),

('tv5monde','TV5MONDE','International French-language television network broadcasting worldwide.',
  (SELECT id FROM public.countries WHERE slug='france'),
  (SELECT id FROM public.categories WHERE slug='entertainment'),
  (SELECT id FROM public.languages WHERE code='fr'),
  '/logos/placeholders/default-tv.svg','https://www.tv5monde.com', false, NULL, ARRAY['french','international']),

('globo','Globo','Brazilian television network with news and entertainment programming.',
  (SELECT id FROM public.countries WHERE slug='brazil'),
  (SELECT id FROM public.categories WHERE slug='entertainment'),
  (SELECT id FROM public.languages WHERE code='pt'),
  '/logos/placeholders/default-tv.svg','https://www.globo.com', false, NULL, ARRAY['brazil','tv']),

('sbt','SBT','Brazilian broadcaster with general entertainment programming.',
  (SELECT id FROM public.countries WHERE slug='brazil'),
  (SELECT id FROM public.categories WHERE slug='entertainment'),
  (SELECT id FROM public.languages WHERE code='pt'),
  '/logos/placeholders/default-tv.svg','https://www.sbt.com.br', false, NULL, ARRAY['brazil','tv']),

('band','Band','Brazilian network broadcasting news, sports, and entertainment.',
  (SELECT id FROM public.countries WHERE slug='brazil'),
  (SELECT id FROM public.categories WHERE slug='news'),
  (SELECT id FROM public.languages WHERE code='pt'),
  '/logos/placeholders/default-tv.svg','https://www.band.uol.com.br', false, NULL, ARRAY['brazil','news']),

('televisa','Televisa','Mexican multimedia company with television networks and programming.',
  (SELECT id FROM public.countries WHERE slug='mexico'),
  (SELECT id FROM public.categories WHERE slug='entertainment'),
  (SELECT id FROM public.languages WHERE code='es'),
  '/logos/placeholders/default-tv.svg','https://www.televisa.com', false, NULL, ARRAY['mexico','tv']),

('tvazteca','TV Azteca','Mexican multimedia company providing news and entertainment channels.',
  (SELECT id FROM public.countries WHERE slug='mexico'),
  (SELECT id FROM public.categories WHERE slug='entertainment'),
  (SELECT id FROM public.languages WHERE code='es'),
  '/logos/placeholders/default-tv.svg','https://www.tvazteca.com', false, NULL, ARRAY['mexico','tv']),

('sky-news','Sky News','UK-based 24-hour international news service (online presence).',
  (SELECT id FROM public.countries WHERE slug='uk'),
  (SELECT id FROM public.categories WHERE slug='news'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://news.sky.com', false, NULL, ARRAY['news','international']),

('bloomberg','Bloomberg','Business and finance news broadcaster with global coverage.',
  (SELECT id FROM public.countries WHERE slug='usa'),
  (SELECT id FROM public.categories WHERE slug='business'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.bloomberg.com', false, NULL, ARRAY['business','finance']),

('cnbc','CNBC','Business news channel reporting on markets and economic news.',
  (SELECT id FROM public.countries WHERE slug='usa'),
  (SELECT id FROM public.categories WHERE slug='business'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.cnbc.com', false, NULL, ARRAY['business','markets']),

('discovery','Discovery Channel','Documentary and factual programming network.',
  (SELECT id FROM public.countries WHERE slug='usa'),
  (SELECT id FROM public.categories WHERE slug='documentary'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.discovery.com', false, NULL, ARRAY['documentary','science']),

('telemundo','Telemundo','U.S.-based Spanish-language network providing news and entertainment.',
  (SELECT id FROM public.countries WHERE slug='usa'),
  (SELECT id FROM public.categories WHERE slug='entertainment'),
  (SELECT id FROM public.languages WHERE code='es'),
  '/logos/placeholders/default-tv.svg','https://www.telemundo.com', false, NULL, ARRAY['spanish','usa']),

('univision','Univision','Spanish-language network in the United States offering news and entertainment.',
  (SELECT id FROM public.countries WHERE slug='usa'),
  (SELECT id FROM public.categories WHERE slug='entertainment'),
  (SELECT id FROM public.languages WHERE code='es'),
  '/logos/placeholders/default-tv.svg','https://www.univision.com', false, NULL, ARRAY['spanish','usa']),

('europe-sports','European Sports Network','Regional sports coverage (placeholder entry).',
  (SELECT id FROM public.countries WHERE slug='germany'),
  (SELECT id FROM public.categories WHERE slug='sports'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.eurosport.com', false, NULL, ARRAY['sports','europe']),

('music-channel','Global Music Channel','Music videos and performance programming (placeholder).',
  (SELECT id FROM public.countries WHERE slug='uk'),
  (SELECT id FROM public.categories WHERE slug='music'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.bbc.co.uk/music', false, NULL, ARRAY['music','entertainment']),

('kids-zone','Kids Zone','Children\'s programming and family-friendly shows (placeholder).',
  (SELECT id FROM public.countries WHERE slug='canada'),
  (SELECT id FROM public.categories WHERE slug='kids'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.cbc.ca/kids', false, NULL, ARRAY['kids','family']),

('science-now','Science Now','Science and technology documentaries and features (placeholder).',
  (SELECT id FROM public.countries WHERE slug='usa'),
  (SELECT id FROM public.categories WHERE slug='science'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.sciencenow.example.com', false, NULL, ARRAY['science','education']),

('lifestyle-tv','Lifestyle TV','Lifestyle and reality programming (placeholder).',
  (SELECT id FROM public.countries WHERE slug='australia'),
  (SELECT id FROM public.categories WHERE slug='lifestyle'),
  (SELECT id FROM public.languages WHERE code='en'),
  '/logos/placeholders/default-tv.svg','https://www.sbs.com.au/lifestyle', false, NULL, ARRAY['lifestyle','home']);

-- End of seed channels
